apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: my-local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-storage
spec:
  storageClassName: my-local-storage
  capacity: 
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/mongo-db/
    type: DirectoryOrCreate